name: Hexo-Blog-Deploy-Actions

on:
  push:
    branches:
      - main  # default branch

jobs:
  pages:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js 16.x
        uses: actions/setup-node@v2.5.1
        with:
          node-version: '16.x'
      - name: Cache NPM dependencies
        uses: actions/cache@v2
        with:
          path: node_modules
          key: ${{ runner.OS }}-npm-cache
          restore-keys: |
            ${{ runner.OS }}-npm-cache
      - name: Change _config.butterfly.yml by env
        env:
          DAOVOICE_APP_ID: ${{ secrets.DAOVOICE_APP_ID }}
          CNZZ_ANALYTICS_ID: ${{ secrets.CNZZ_ANALYTICS_ID }}
          BAIDU_ANALYTICS: ${{ secrets.BAIDU_ANALYTICS }}
        run: envsubst < _config.butterfly_temp.yml > _config.butterfly.yml
      - name: Install Dependencies
        run: npm install
      - name: Build
        run: npm run build
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          deploy_key: ${{ secrets.ACTIONS_DEPLOY_KEY }}
          external_repository: Deebl/Deebl.github.io
          publish_dir: ./public
          cname: blog.aiwan.run
          commit_message: ${{ github.event.head_commit.message }}
          publish_branch: gh-pages  # deploying branch